id: I72756D29
legacy_id: P004517
ocr_import_info:
  bdrc_scan_id: W1KG12171
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:41:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:24:20.415475+00:00'
last_modified: 2022-08-31 11:24:36.119566
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12171
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12171
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བར་དོའི་གསལ་འདེབས་ཐོས་གྲོལ་ཆེན་མོ་བཀླག་ཆོག་ཏུ་བཀོད་པ་འཁྲུལ་སྣང་རང་གྲོལ་དང་སྨོན་ལམ་ཁག་ཅིག
  author: རྫོགས་ཆེན ༠༣་ངེས་དོན་བསྟན་འཛིན་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6921651005063785
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1KG12184:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12184
      total_pages: 598
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12184.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6921651005063785
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
