id: P004517
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12171
  title: བར་དོའི་གསལ་འདེབས་ཐོས་གྲོལ་ཆེན་མོ་བཀླག་ཆོག་ཏུ་བཀོད་པ་འཁྲུལ་སྣང་རང་གྲོལ་དང་སྨོན་ལམ་ཁག་ཅིག
  author: ''
  volumes: {}
